export const previewData = [
    {
        id: '0a9xx00000007pVAAQ',
        name: 'SolarFlex Pro 10AWG Cable',
        quantity: 3,
        type: 'Product',
        itemizedAdjustmentAmount: 0,
        salesPrice: 9,
        adjustmentAmount: 0,
        amount: 27,
        listPrice: 0,
        price: 27,
        tax: undefined,
        unitAdjustedPrice: 9,
        unitAdjustmentAmount: 0,
        productDetails: {
            name: 'SolarFlex Pro 10AWG Cable',
            productId: '01txx0000006i2rAAA',
            purchaseQuantityRule: undefined,
            sku: '6010048',
            fields: {
                Description:
                    "Flexible and durable solar cable designed for easy installation and long-lasting performance.",
                ProductCode: '6010048',
                Family: 'Solar Cables',
                StockKeepingUnit: '6010048',
                CurrencyIsoCode: 'USD',
                Name: 'SolarFlex Pro 10AWG Cable',
            },
            thumbnailImage: {
                alternateText: 'SolarFlex Pro 10AWG Cable',
                contentVersionId: null,
                id: '2pmxx0000000085AAA',
                mediaType: 'Image',
                sortOrder: 0,
                thumbnailUrl: null,
                title: 'northerntrailoutfitterscom-nto-alpine-nutrition-default-images-large-barsboxof6gogreentealargepng',
                url: 'https://sfdc-ckz-b2b.s3.amazonaws.com/SDO/2021/Connector+Cables/Connector+Cables+1.png',
            },
            variationAttributes: {},
            productSubscriptionInformation: undefined,
        },
        Messages: [],
        subscriptionId: undefined,
        subscriptionTermUnit: undefined,
        subscriptionTerm: undefined,
        subscriptionType: undefined,
    },
    {
        id: '0a9xx00000007pAAAQ',
        name: 'PowerLink Pro Connector Kit',
        quantity: 9,
        type: 'Product',
        salesPrice: 22.5,
        itemizedAdjustmentAmount: -13.5,
        adjustmentAmount: -13.5,
        amount: 189,
        listPrice: 202.5,
        price: 189,
        tax: undefined,
        unitAdjustedPrice: 22.5,
        unitAdjustmentAmount: 0,
        productDetails: {
            name: 'PowerLink Pro Connector Kit',
            productId: '01txx0000006iDjAAI',
            purchaseQuantityRule: undefined,
            sku: '6010046',
            fields: {
                Description: 'Professional-grade cable connectors for a secure and reliable solar power system installation.',
                ProductCode: '6010046',
                QuantityUnitOfMeasure: null,
                Family: 'Cable Accessories',
                StockKeepingUnit: '6010046',
                CurrencyIsoCode: 'USD',
                Name: 'PowerLink Pro Connector Kit',
            },
            thumbnailImage: {
                alternateText: 'PowerLink Pro Connector Kit',
                contentVersionId: null,
                id: '2pmxx0000000085AAA',
                mediaType: 'Image',
                sortOrder: 0,
                thumbnailUrl: null,
                title: 'northerntrailoutfitterscom-nto-alpine-nutrition-default-images-large-barsboxof6gogreentealargepng',
                url: 'https://sfdc-ckz-b2b.s3.amazonaws.com/SDO/2021/Yaw+Motor/Yaw+Motor1.png',
            },
            variationAttributes: {
                Flavor__c: {
                    label: 'Flavor',
                    value: 'Chocolate',
                    apiName: 'flavor',
                    sequence: 1,
                },
                Size__c: {
                    label: 'Size',
                    value: '500mL',
                    apiName: 'size',
                    sequence: 1,
                },
            },
            productSubscriptionInformation: undefined,
        },
        Messages: [],
        subscriptionId: undefined,
        subscriptionTermUnit: undefined,
        subscriptionTerm: undefined,
        subscriptionType: undefined,
    },
    {
        id: '0a9xx00000007pBCAQ',
        name: 'SolarMax Ultra 500W',
        quantity: 1,
        type: 'Product',
        itemizedAdjustmentAmount: 0,
        salesPrice: 9,
        adjustmentAmount: 0,
        amount: 27,
        listPrice: 0,
        price: 27,
        tax: undefined,
        unitAdjustedPrice: 9,
        unitAdjustmentAmount: 0,
        productDetails: {
            name: 'SolarMax Ultra 500W',
            productId: '01txx0000006i2rAAA',
            purchaseQuantityRule: undefined,
            sku: '6010048',
            fields: {
                Description:
                    "High-efficiency solar panel with cutting-edge technology for maximum power generation.",
                ProductCode: '6010048',
                Family: 'Solar Panels',
                StockKeepingUnit: '6010048',
                CurrencyIsoCode: 'USD',
                Name: 'SolarMax Ultra 500W',
            },
            thumbnailImage: {
                alternateText: 'SolarMax Ultra 500W',
                contentVersionId: null,
                id: '2pmxx0000000085AAA',
                mediaType: 'Image',
                sortOrder: 0,
                thumbnailUrl: null,
                title: 'northerntrailoutfitterscom-nto-alpine-nutrition-default-images-large-barsboxof6gogreentealargepng',
                url: 'https://sfdc-ckz-b2b.s3.amazonaws.com/SDO/2021/Solar+Panel/Solar+Panel+1.png',
            },
            variationAttributes: {},
            productSubscriptionInformation: undefined,
        },
        Messages: [],
        subscriptionId: '0jPxx000000004rEAA',
        subscriptionTermUnit: 'Monthly',
        subscriptionTerm: undefined,
        subscriptionType: 'Evergreen',
    }
];
